### ISSUE TITLE
API Restructure

### ISSUE THREAD

**Issue by rbmrclo** [ninariccimarie/quiz-master#3]
### Background
We will start using the backend code as our API service. One of the things that we need to polish is to make it more RESTful and adheres to the convention of naming API routes.

### Before

```
$ rake routes

GET    /questions
POST   /questions
GET    /questions/:id
GET    /questions/new
GET    /questions/:id/edit
PUT    /questions/:id
PATCH  /questions/:id
DELETE /questions/:id
POST   /questions/:id
```

### After

```
GET    /api/questions
POST   /api/questions          
GET    /api/questions/:id
PUT    /api/questions/:id
PATCH  /api/questions/:id
DELETE /api/questions/:id
POST   /api/questions/:id/answers
```

### TODOs
- [x] Move questions endpoints under API namespace
- [x] Please add versioning for the API endpoints
- [x] Please add token authentication for all API requests
- [x] Remove unnecessary routes
- [x] Follow [2 spaces](https://github.com/bbatsov/ruby-style-guide#spaces-indentation) convention

**Comment by rbmrclo** [comment]
Secrets: http://brandonhilkert.com/blog/using-rails-4-dot-1-secrets-for-configuration/
