### ISSUE TITLE
Support I18n for PH

### ISSUE THREAD

**Issue by rbmrclo** [ninariccimarie/quiz-master#4]
### Background

We will now start expanding our team in the Philippines 🇵🇭 ! First step that we need to do is to support the language of the country. One example is this part of our code:

- https://github.com/ninariccimarie/quiz-master/blob/master/backend/app/controllers/questions_controller.rb#L43

When the student got a correct answer for the question, we are displaying a success message in English language. 

-  "Yay! You're correct!"

### Request

- If the current user is from the Philippines, instead of displaying the language in English, we want to display it in Filipino language instead.

### TODO
- [x] Setup I18n for the backend app
- [x] Update `en.yml` and introduce `en-PH.yml` 
- [x] Remove all hardcoded strings inside our codebase and display the messages by using [`I18n.t`](http://guides.rubyonrails.org/i18n.html)

**Comment by rbmrclo** [comment]
Thanks @ninariccimarie!
