### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by rbmrclo** [ninariccimarie/quiz-master#7]
### Background

The strategy and planning team needs to create a report on how to track the KPI for Weekly Active Learners. WAL is measured by how many questions are being answered every week by an individual student.

### Feature

By using [`rails_admin`](https://github.com/sferik/rails_admin), create an admin dashboard page where we could see the count of questions and answers in our database.

### TODO
- [x] Show the `Answer` and `Question` count in the home page of the admin dashboard
- [x] Admin should be able to create, update, and delete a question
- [ ] Upon visiting the admin page, an HTTP basic authentication should prompt to the user before proceeding. Failure to submit a valid credentials must result to prevention of access to our admin dashboard.

**Comment by ninariccimarie** [comment]
@rbmrclo I think there's a conflict between the 2nd and 3rd todo? or did I misunderstood it?

**Comment by rbmrclo** [comment]
@ninariccimarie Thanks for the catch! I actually meant `answer` for the 3rd todo instead of `question`. I updated it now.

**Comment by rbmrclo** [comment]
Thinking of it again, I think we need crud for the `answers`, let me update.

**Comment by ninariccimarie** [comment]
how about for the `client`? any specifics?

**Comment by rbmrclo** [comment]
For the `client`, I presume that you'll be using it for the basic authentication, you can freely use the `name` as username and `token` as password.

**Comment by ninariccimarie** [comment]
ah yes, or will it be convenient to have a password separate from the token? Where in the name is for the username and I'll add password for the password since the token is a randomly generated string it will be hard to remember or the user will have to store the token somewhere. (just thinking about the real world scenario)

**Comment by rbmrclo** [comment]
@ninariccimarie As expected from you, it's definitely the better approach! 🎉  
Please do it for the sake of better architecture. Good thinking!

**Comment by ninariccimarie** [comment]
thank you very much. I thought of it this way since you're also preparing me for the on boarding and also I was absorbing your approach. :)
